# Generated by Django 2.2.1 on 2019-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190522_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
