# Generated by Django 2.2.1 on 2019-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190526_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
